version: '3.6'
x-logging:
  options:
    max-size: '20m'
    max-file: '2'
services:
  test1:
    image: reg-harbor.agiletechnologies.in/test1/test1:latest
    hostname: test1
    container_name: test1
    networks:
        - default
    ports:
        - 7171:80
networks:
  default:
    name: test1
