version: '3.6'
services:
  devcontainer:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
        - default
    ports:
        - 7171:80
networks:
  default:
    name: devcontainer
