namespace Vessels.Helper
{
    public static class ExcelFieldData
    {
        public static Dictionary<ExcelReportFields, string> ExcelReportField = new Dictionary<ExcelReportFields, string>()
        {
            { ExcelReportFields.LatitudeDeg, "LatitudeDeg" },
            { ExcelReportFields.LatitudeMin, "LatitudeMin" },
            { ExcelReportFields.LatitudeSec, "LatitudeSec" },
            { ExcelReportFields.LatitudeDir, "LatitudeDir" },
            { ExcelReportFields.LongitudeDeg, "LongitudeDeg" },
            { ExcelReportFields.LongitudeMin, "LongitudeMin" },
            { ExcelReportFields.LongitudeSec, "LongitudeSec" },
            { ExcelReportFields.LongitudeDir, "LongitudeDir" },
            { ExcelReportFields.Date, "Date" },
            { ExcelReportFields.Time, "Time" },
            { ExcelReportFields.LocalTime, "LocalTime" },
            { ExcelReportFields.CurrentPort, "CurrentPort" },
            { ExcelReportFields.ArrivalPort, "ArrivalPort" },
            { ExcelReportFields.DeparturePort, "DeparturePort" },
            { ExcelReportFields.UTCTimestamp, "UTCTimestamp" },
            { ExcelReportFields.UTC_Timestamp, "UTC Timestamp" },
            { ExcelReportFields.ETDUTCTimestamp, "ETDUTCTimestamp" },
            { ExcelReportFields.ETDUTCOffset, "ETDUTCOffset" },
            { ExcelReportFields.DraftAftm, "DraftAftm" },
            { ExcelReportFields.DraftForem, "DraftForem" },
            { ExcelReportFields.GeneralRemarks, "GeneralRemarks" },
            { ExcelReportFields.VesselConditionBallastLaden, "VesselConditionBallastLaden" },
            { ExcelReportFields.ChiefEngineer, "ChiefEngineer" },
            { ExcelReportFields.Master, "Master" },
            { ExcelReportFields.VesselIMO, "VesselIMO" },
            { ExcelReportFields.VesselName, "VesselName" },
            { ExcelReportFields.ReportType, "ReportType" },
            { ExcelReportFields.AverageRPM, "AverageRPM" },
            { ExcelReportFields.BeaufortForce, "BeaufortForce" },
            { ExcelReportFields.InstructedSpeedkn, "InstructedSpeedkn" },
            { ExcelReportFields.InstructedRPM, "InstructedRPM" },
            { ExcelReportFields.LoggedDistancenm, "LoggedDistancenm" },
            { ExcelReportFields.MEPowerkW, "MEPowerkW" },
            { ExcelReportFields.ObservedDistancenm, "ObservedDistancenm" },
            { ExcelReportFields.Slip, "Slip" },
            { ExcelReportFields.SpeedOverGroundkn, "SpeedOverGroundkn" },
            { ExcelReportFields.SpeedThroughWaterkn, "SpeedThroughWaterkn" },
            { ExcelReportFields.SteamingHoursSinceLastReport, "SteamingHoursSinceLastReport" },
            { ExcelReportFields.ManouveringHours, "ManouveringHours" },
            { ExcelReportFields.DSS, "DSS" },
            { ExcelReportFields.HoursSinceLastReport, "HoursSinceLastReport" },
            { ExcelReportFields.StoppageRemarks, "StoppageRemarks" },
            { ExcelReportFields.StoppageHours, "StoppageHours" },
            { ExcelReportFields.CargoLoad, "CargoLoad" },
            { ExcelReportFields.WindDirection, "WindDirection" },
            { ExcelReportFields.CargoDischarge, "CargoDischarge" },
            { ExcelReportFields.RemarksforOtherCons, "RemarksforOtherCons" },
            { ExcelReportFields.TotalCargoOnBoard, "TotalCargoOnBoard" },
            { ExcelReportFields.ETATimestampUTC, "ETATimestampUTC" },
            { ExcelReportFields.DistancetoDestination, "DistancetoDestination" },
            { ExcelReportFields.UpcomingPort, "UpcomingPort" },
            { ExcelReportFields.ETAUTCOffset, "ETAUTCOffset" },
            { ExcelReportFields.UTCOffset, "UTCOffset" },
            { ExcelReportFields.AETotalConsumption_LGO, "AETotalConsumption_LGO" },
            { ExcelReportFields.BoilerTotalConsumption_LGO, "BoilerTotalConsumption_LGO" },
            { ExcelReportFields.MainEngineTotal_LGO, "MainEngineTotal_LGO" },
            { ExcelReportFields.TotalConsumption_LGO, "TotalConsumption_LGO" },
            { ExcelReportFields.AETotalConsumption_LFO, "AETotalConsumption_LFO" },
            { ExcelReportFields.BoilerTotalConsumption_LFO, "BoilerTotalConsumption_LFO" },
            { ExcelReportFields.MainEngineTotal_LFO, "MainEngineTotal_LFO" },
            { ExcelReportFields.TotalConsumption_LFO, "TotalConsumption_LFO" },
            { ExcelReportFields.AETotalConsumption_IFO, "AETotalConsumption_IFO" },
            { ExcelReportFields.BoilerTotalConsumption_IFO, "BoilerTotalConsumption_IFO" },
            { ExcelReportFields.MainEngineTotal_IFO, "MainEngineTotal_IFO" },
            { ExcelReportFields.TotalConsumption_IFO, "TotalConsumption_IFO" },
            { ExcelReportFields.AETotalConsumption_MGO, "AETotalConsumption_MGO" },
            { ExcelReportFields.BoilerTotalConsumption_MGO, "BoilerTotalConsumption_MGO" },
            { ExcelReportFields.MainEngineTotal_MGO, "MainEngineTotal_MGO" },
            { ExcelReportFields.TotalConsumption_MGO, "TotalConsumption_MGO" },
            { ExcelReportFields.ROB_MGO, "ROB_MGO" },
            { ExcelReportFields.ROB_LFO, "ROB_LFO" },
            { ExcelReportFields.ROB_LGO, "ROB_LGO" },
            { ExcelReportFields.ROB_IFO, "ROB_IFO" },
            { ExcelReportFields.CargoDischargingAE_IFO, "CargoDischargingAE_IFO" },
            { ExcelReportFields.CargoDischargingAE_LGO, "CargoDischargingAE_LGO" },
            { ExcelReportFields.CargoDischargingAE_MGO, "CargoDischargingAE_MGO" },
            { ExcelReportFields.CargoDischargingAE_LFO, "CargoDischargingAE_LFO" },
            { ExcelReportFields.CargoDischargingBoiler_IFO, "CargoDischargingBoiler_IFO" },
            { ExcelReportFields.CargoDischargingBoiler_LGO, "CargoDischargingBoiler_LGO" },
            { ExcelReportFields.CargoDischargingBoiler_MGO, "CargoDischargingBoiler_MGO" },
            { ExcelReportFields.CargoDischargingBoiler_LFO, "CargoDischargingBoiler_LFO" },
            { ExcelReportFields.CargoLoadingAE_IFO, "CargoLoadingAE_IFO" },
            { ExcelReportFields.CargoLoadingAE_LGO, "CargoLoadingAE_LGO" },
            { ExcelReportFields.CargoLoadingAE_MGO, "CargoLoadingAE_MGO" },
            { ExcelReportFields.CargoLoadingAE_LFO, "CargoLoadingAE_LFO" },
            { ExcelReportFields.CargoLoadingBoiler_IFO, "CargoLoadingBoiler_IFO" },
            { ExcelReportFields.CargoLoadingBoiler_LGO, "CargoLoadingBoiler_LGO" },
            { ExcelReportFields.CargoLoadingBoiler_MGO, "CargoLoadingBoiler_MGO" },
            { ExcelReportFields.CargoLoadingBoiler_LFO, "CargoLoadingBoiler_LFO" },
            { ExcelReportFields.BunkerSupplied_IFO, "BunkerSupplied_IFO" },
            { ExcelReportFields.BunkerSupplied_LGO, "BunkerSupplied_LGO" },
            { ExcelReportFields.BunkerSupplied_MGO, "BunkerSupplied_MGO" },
            { ExcelReportFields.BunkerSupplied_LFO, "BunkerSupplied_LFO" },
            { ExcelReportFields.BunkerAdjustment_IFO, "BunkerAdjustment_IFO" },
            { ExcelReportFields.BunkerAdjustment_LGO, "BunkerAdjustment_LGO" },
            { ExcelReportFields.BunkerAdjustment_MGO, "BunkerAdjustment_MGO" },
            { ExcelReportFields.BunkerAdjustment_LFO, "BunkerAdjustment_LFO" },
            { ExcelReportFields.BallastWaterAE_LGO, "BallastWaterAE_LGO" },
            { ExcelReportFields.BallastWaterBoiler_LGO, "BallastWaterBoiler_LGO" },
            { ExcelReportFields.CargoHeatingAE_LGO, "CargoHeatingAE_LGO" },
            { ExcelReportFields.CargoHeatingBoiler_LGO, "CargoHeatingBoiler_LGO" },
            { ExcelReportFields.IGSAE_LGO, "IGSAE_LGO" },
            { ExcelReportFields.IGSBoiler_LGO, "IGSBoiler_LGO" },
            { ExcelReportFields.MainEngine_LGO, "MainEngine_LGO" },
            { ExcelReportFields.OtherAE_LGO, "OtherAE_LGO" },
            { ExcelReportFields.OtherBoiler_LGO, "OtherBoiler_LGO" },
            { ExcelReportFields.StandardAE_LGO, "StandardAE_LGO" },
            { ExcelReportFields.StandardBoiler_LGO, "StandardBoiler_LGO" },
            { ExcelReportFields.TankCleaningAE_LGO, "TankCleaningAE_LGO" },
            { ExcelReportFields.TankCleaningBoiler_LGO, "TankCleaningBoiler_LGO" },
            { ExcelReportFields.BallastWaterAE_IFO, "BallastWaterAE_IFO" },
            { ExcelReportFields.BallastWaterBoiler_IFO, "BallastWaterBoiler_IFO" },
            { ExcelReportFields.CargoHeatingAE_IFO, "CargoHeatingAE_IFO" },
            { ExcelReportFields.CargoHeatingBoiler_IFO, "CargoHeatingBoiler_IFO" },
            { ExcelReportFields.IGSAE_IFO, "IGSAE_IFO" },
            { ExcelReportFields.IGSBoiler_IFO, "IGSBoiler_IFO" },
            { ExcelReportFields.MainEngine_IFO, "MainEngine_IFO" },
            { ExcelReportFields.OtherAE_IFO, "OtherAE_IFO" },
            { ExcelReportFields.OtherBoiler_IFO, "OtherBoiler_IFO" },
            { ExcelReportFields.StandardAE_IFO, "StandardAE_IFO" },
            { ExcelReportFields.StandardBoiler_IFO, "StandardBoiler_IFO" },
            { ExcelReportFields.TankCleaningAE_IFO, "TankCleaningAE_IFO" },
            { ExcelReportFields.TankCleaningBoiler_IFO, "TankCleaningBoiler_IFO" },
            { ExcelReportFields.BallastWaterAE_MGO, "BallastWaterAE_MGO" },
            { ExcelReportFields.BallastWaterBoiler_MGO, "BallastWaterBoiler_MGO" },
            { ExcelReportFields.CargoHeatingAE_MGO, "CargoHeatingAE_MGO" },
            { ExcelReportFields.CargoHeatingBoiler_MGO, "CargoHeatingBoiler_MGO" },
            { ExcelReportFields.IGSAE_MGO, "IGSAE_MGO" },
            { ExcelReportFields.IGSBoiler_MGO, "IGSBoiler_MGO" },
            { ExcelReportFields.MainEngine_MGO, "MainEngine_MGO" },
            { ExcelReportFields.OtherAE_MGO, "OtherAE_MGO" },
            { ExcelReportFields.OtherBoiler_MGO, "OtherBoiler_MGO" },
            { ExcelReportFields.StandardAE_MGO, "StandardAE_MGO" },
            { ExcelReportFields.StandardBoiler_MGO, "StandardBoiler_MGO" },
            { ExcelReportFields.TankCleaningAE_MGO, "TankCleaningAE_MGO" },
            { ExcelReportFields.TankCleaningBoiler_MGO, "TankCleaningBoiler_MGO" },
            { ExcelReportFields.BallastWaterAE_LFO, "BallastWaterAE_LFO" },
            { ExcelReportFields.BallastWaterBoiler_LFO, "BallastWaterBoiler_LFO" },
            { ExcelReportFields.CargoHeatingAE_LFO, "CargoHeatingAE_LFO" },
            { ExcelReportFields.CargoHeatingBoiler_LFO, "CargoHeatingBoiler_LFO" },
            { ExcelReportFields.IGSAE_LFO, "IGSAE_LFO" },
            { ExcelReportFields.IGSBoiler_LFO, "IGSBoiler_LFO" },
            { ExcelReportFields.MainEngine_LFO, "MainEngine_LFO" },
            { ExcelReportFields.OtherAE_LFO, "OtherAE_LFO" },
            { ExcelReportFields.OtherBoiler_LFO, "OtherBoiler_LFO" },
            { ExcelReportFields.StandardAE_LFO, "StandardAE_LFO" },
            { ExcelReportFields.StandardBoiler_LFO, "StandardBoiler_LFO" },
            { ExcelReportFields.TankCleaningAE_LFO, "TankCleaningAE_LFO" },
            { ExcelReportFields.TankCleaningBoiler_LFO, "TankCleaningBoiler_LFO" },
            { ExcelReportFields.CargoCoolingAE_LGO, "CargoCoolingAE_LGO" },
            { ExcelReportFields.CargoCoolingBoiler_LGO, "CargoCoolingBoiler_LGO" },
            { ExcelReportFields.CargoCoolingAE_IFO, "CargoCoolingAE_IFO" },
            { ExcelReportFields.CargoCoolingBoiler_IFO, "CargoCoolingBoiler_IFO" },
            { ExcelReportFields.CargoCoolingAE_MGO, "CargoCoolingAE_MGO" },
            { ExcelReportFields.CargoCoolingBoiler_MGO, "CargoCoolingBoiler_MGO" },
            { ExcelReportFields.CargoCoolingAE_LFO, "CargoCoolingAE_LFO" },
            { ExcelReportFields.CargoCoolingBoiler_LFO, "CargoCoolingBoiler_LFO" },
            { ExcelReportFields.ETAUTCTimestamp, "ETAUTCTimestamp" }
        };
    }



    public enum ExcelReportFields
    {
        #region Latitude
        LatitudeDeg,
        LatitudeMin,
        LatitudeSec,
        LatitudeDir,
        #endregion
        #region Longitude
        LongitudeDeg,
        LongitudeMin,
        LongitudeSec,
        LongitudeDir,
        #endregion
        Date,
        Time,
        LocalTime,
        CurrentPort,
        ArrivalPort,
        DeparturePort,
        UTC_Timestamp,
        UTCTimestamp,
        ETDUTCTimestamp,
        ETDUTCOffset,
        DraftAftm,
        DraftForem,
        GeneralRemarks,
        VesselConditionBallastLaden,
        ChiefEngineer,
        Master,
        VesselIMO,
        VesselName,
        ReportType,
        AverageRPM,
        BeaufortForce,
        InstructedSpeedkn,
        InstructedRPM,
        LoggedDistancenm,
        MEPowerkW,
        ObservedDistancenm,
        Slip,
        SpeedOverGroundkn,
        SpeedThroughWaterkn,
        SteamingHoursSinceLastReport,
        ManouveringHours,
        DSS,
        HoursSinceLastReport,
        StoppageRemarks,
        StoppageHours,
        CargoLoad,
        WindDirection,
        CargoDischarge,
        RemarksforOtherCons,
        TotalCargoOnBoard,
        UTCOffset,
        #region UpComming Port
        ETATimestampUTC,
        DistancetoDestination,
        UpcomingPort,
        ETAUTCOffset,
        #endregion

        #region TotalConsumption
        AETotalConsumption_LGO,
        BoilerTotalConsumption_LGO,
        MainEngineTotal_LGO,
        TotalConsumption_LGO,
        AETotalConsumption_LFO,
        BoilerTotalConsumption_LFO,
        MainEngineTotal_LFO,
        TotalConsumption_LFO,
        AETotalConsumption_IFO,
        BoilerTotalConsumption_IFO,
        MainEngineTotal_IFO,
        TotalConsumption_IFO,
        AETotalConsumption_MGO,
        BoilerTotalConsumption_MGO,
        MainEngineTotal_MGO,
        TotalConsumption_MGO,
        #endregion

        #region ROB
        ROB_MGO,
        ROB_LFO,
        ROB_LGO,
        ROB_IFO,
        #endregion,
        CargoDischargingAE_IFO,
        CargoDischargingAE_LGO,
        CargoDischargingAE_MGO,
        CargoDischargingAE_LFO,
        CargoDischargingBoiler_IFO,
        CargoDischargingBoiler_LGO,
        CargoDischargingBoiler_MGO,
        CargoDischargingBoiler_LFO,
        CargoLoadingAE_IFO,
        CargoLoadingAE_LGO,
        CargoLoadingAE_MGO,
        CargoLoadingAE_LFO,
        CargoLoadingBoiler_IFO,
        CargoLoadingBoiler_LGO,
        CargoLoadingBoiler_MGO,
        CargoLoadingBoiler_LFO,
        BunkerSupplied_IFO,
        BunkerSupplied_LGO,
        BunkerSupplied_MGO,
        BunkerSupplied_LFO,
        BunkerAdjustment_IFO,
        BunkerAdjustment_LGO,
        BunkerAdjustment_MGO,
        BunkerAdjustment_LFO,
        BallastWaterAE_LGO,
        BallastWaterBoiler_LGO,
        CargoHeatingAE_LGO,
        CargoHeatingBoiler_LGO,
        IGSAE_LGO,
        IGSBoiler_LGO,
        MainEngine_LGO,
        OtherAE_LGO,
        OtherBoiler_LGO,
        StandardAE_LGO,
        StandardBoiler_LGO,
        TankCleaningAE_LGO,
        TankCleaningBoiler_LGO,
        BallastWaterAE_IFO,
        BallastWaterBoiler_IFO,
        CargoHeatingAE_IFO,
        CargoHeatingBoiler_IFO,
        IGSAE_IFO,
        IGSBoiler_IFO,
        MainEngine_IFO,
        OtherAE_IFO,
        OtherBoiler_IFO,
        StandardAE_IFO,
        StandardBoiler_IFO,
        TankCleaningAE_IFO,
        TankCleaningBoiler_IFO,
        BallastWaterAE_MGO,
        BallastWaterBoiler_MGO,
        CargoHeatingAE_MGO,
        CargoHeatingBoiler_MGO,
        IGSAE_MGO,
        IGSBoiler_MGO,
        MainEngine_MGO,
        OtherAE_MGO,
        OtherBoiler_MGO,
        StandardAE_MGO,
        StandardBoiler_MGO,
        TankCleaningAE_MGO,
        TankCleaningBoiler_MGO,
        BallastWaterAE_LFO,
        BallastWaterBoiler_LFO,
        CargoHeatingAE_LFO,
        CargoHeatingBoiler_LFO,
        IGSAE_LFO,
        IGSBoiler_LFO,
        MainEngine_LFO,
        OtherAE_LFO,
        OtherBoiler_LFO,
        StandardAE_LFO,
        StandardBoiler_LFO,
        TankCleaningAE_LFO,
        TankCleaningBoiler_LFO,
        CargoCoolingAE_LGO,
        CargoCoolingBoiler_LGO,
        CargoCoolingAE_IFO,
        CargoCoolingBoiler_IFO,
        CargoCoolingAE_MGO,
        CargoCoolingBoiler_MGO,
        CargoCoolingAE_LFO,
        CargoCoolingBoiler_LFO,
        ETAUTCTimestamp,

    }


}
